<template>
  <div class="studio" v-if="project">
    <aside><h2>ROM Editor</h2><button v-for="(label,key) in sections" :key="key" :class="{selected:section===key}" @click="navigate(key)">{{label}}</button><p>{{patches.length}} recursos modificados</p><small>{{saveStatus}}</small><button v-if="saveError" @click="retrySave">Reintentar guardado</button></aside>
    <div class="workspace">
      <header><button @click="history(false)" :disabled="!canUndo">↶ Deshacer</button><button @click="history(true)" :disabled="!canRedo">↷ Rehacer</button><button class="primary" @click="exportRom">Exportar ROM</button></header>
      <p v-if="error" role="alert" class="error">{{error}}</p><p v-if="saveError" role="alert" class="error">{{saveError}} Descarga un proyecto para respaldar tus cambios.</p>
      <section v-if="section==='dashboard'"><h2>International Superstar Soccer Deluxe</h2><p>36 equipos · 720 jugadores · {{audioSamples.length}} muestras BRR. Las modificaciones se guardan por hash de la ROM original.</p><p>Los equipos ocupan slots fijos. Agregar/eliminar o reordenar requiere modificar código y referencias del juego; estas operaciones están pendientes de ingeniería inversa.</p><p>Los nombres de equipo usados por el juego se editan como rótulos gráficos. Las etiquetas del selector identifican los slots originales.</p><p>Para empezar selecciona Jugadores, Apariencia, Gráficos o Audio. La ROM exportada conserva tamaño, mapeo y cabecera; los cambios recalculan checksum y complemento.</p><details><summary>Estructuras aún pendientes</summary><p>Foto de equipo y cinco fotos de portada y composición de pantalla principal. El logo ya se compone con sus mapas, sprites y paletas originales.</p><p>Pitch por evento, secuencias musicales y bucles del SPC700 pendientes. La previsualización de muestras usa el pitch de inspección elegido, sin afirmar reproducción idéntica al juego.</p></details></section>
      <template v-if="['teams','players','appearance','graphics'].includes(section)">
        <label>Equipo <select :value="teamIndex" @change="changeTeam($event)"><option v-for="(name,i) in teams" :key="i" :value="i">{{i+1}}. {{name}}</option></select></label>
      </template>
      <section v-if="section==='teams'"><h2>Información general · {{teams[teamIndex]}}</h2><p>Nombre en juego: rótulo gráfico 2bpp de 32 × 8. La etiqueta del selector identifica el slot original.</p><RomImage :matrix="team.teamMatrix" :colors="team.teamColors" label="Nombre gráfico del equipo" /><button @click="editTeamLabel">Editar rótulo</button><h3>Formación {{formation.label}}</h3><p>Se copian etiqueta, posiciones y roles de una formación original. Revisa que las posiciones de tus jugadores sean adecuadas; la plantilla no cambia automáticamente.</p><svg viewBox="0 0 120 100" class="pitch" role="img" :aria-label="`Formación ${formation.label}`"><rect x="1" y="1" width="118" height="98" fill="#248249" stroke="white" /><path d="M1 50H119" stroke="white"/><circle cx="60" cy="50" r="12" fill="none" stroke="white"/><g v-for="(slot,i) in formation.slots" :key="i"><circle :cx="60+slot.width" :cy="formationY(slot)" r="5" fill="white"/><text :x="60+slot.width" :y="formationY(slot)+2" text-anchor="middle" font-size="5" fill="#172a40">{{slot.role===1||slot.role===5?'DF':slot.role===2||slot.role===6?'MF':'FW'}}</text></g></svg><label>Formación original <select v-model.number="formationSource"><option v-for="(name,i) in teams" :key="i" :value="i">{{name}} · {{formationOf(i).label}}</option></select></label><button @click="applyFormation">Aplicar formación</button><button @click="restoreResource(formation.id)" :disabled="!isModified(formation.id)">Restaurar formación</button></section>
      <section v-if="section==='players'">
        <h2>Jugadores · {{teams[teamIndex]}}</h2><p>Dorsales/identificadores únicos (1–20): elegir uno ya asignado intercambia ambos valores.</p>
        <div class="toolbar"><input v-model="search" placeholder="Buscar jugador" aria-label="Buscar jugador" /><select v-model="positionFilter" aria-label="Filtrar posición"><option value="">Todas las posiciones</option><option v-for="(name,id) in positions" :key="id" :value="id">{{name}}</option></select><label>Orden <select v-model="sortKey"><option value="index">Slot</option><option value="no">Dorsal</option><option value="name">Nombre</option><option value="position">Posición</option></select></label></div>
        <div class="toolbar"><span>{{selectedPlayers.length}} seleccionados</span><select v-model="batchStat" aria-label="Atributo para cambio múltiple"><option v-for="s in stats" :key="s">{{s}}</option></select><input type="number" min="1" max="10" v-model.number="batchValue" aria-label="Valor para cambio múltiple" /><button @click="batch" :disabled="!selectedPlayers.length">Aplicar a seleccionados</button><label>Copiar plantilla <select v-model.number="copySource"><option v-for="(name,i) in teams" :key="i" :value="i">{{name}}</option></select></label><button @click="copyRoster">Copiar sus 20 jugadores</button></div>
        <div class="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Seleccionar jugadores visibles" @change="selectAll($event.target.checked)" /></th><th>Dorsal</th><th>Nombre</th><th>Posición</th><th>Pelo</th><th>Piel</th><th>Atributos</th><th>Restaurar</th></tr></thead>
          <tbody><tr v-for="row in rows" :key="row.index" :class="{modified:isPlayerModified(row.index)}"><td><input type="checkbox" :value="row.index" v-model="selectedPlayers" :aria-label="`Seleccionar ${row.player.name}`" /></td><td><input class="number" type="number" min="1" max="20" :value="row.player.no" @change="editPlayer(row.index,'no',Number($event.target.value),$event)" /></td><td><input class="name" maxlength="8" :value="row.player.name" @change="editPlayer(row.index,'name',$event.target.value,$event)" /></td><td><select :value="row.player.position" @change="editPlayer(row.index,'position',Number($event.target.value),$event)"><option v-for="(name,id) in positions" :key="id" :value="id">{{name}}</option></select></td>
            <td><button class="hair" @click="hairPlayer=row.index"><RomImage compact :matrix="row.player.head" :colors="row.player.headColors" :label="`Pelo ${row.player.hair}`" />{{row.player.hair}}</button></td>
            <td><div class="skin-cell"><input type="color" class="skin-color" :value="row.player.skinColor" @change="skinColor(row.index,$event.target.value,$event)" :title="'Edita un color de paleta; puede afectar varios jugadores'" /><select :value="row.player.skin" @change="editPlayer(row.index,'skin',Number($event.target.value),$event)"><option :value="0">Normal</option><option :value="1">Alternativa</option></select></div></td>
            <td><details><summary>Estadísticas</summary><label v-for="stat in stats" :key="stat">{{stat}} <input class="number" type="number" min="1" max="10" :value="row.player[stat]" @change="editPlayer(row.index,stat,Number($event.target.value),$event)" /></label></details></td><td><button @click="restorePlayer(row.index)" :disabled="!isPlayerModified(row.index)">↺</button></td></tr></tbody></table></div>
      </section>
      <section v-if="section==='appearance'"><h2>Uniformes y portero</h2><label>Paleta <select v-model.number="paletteTable"><option :value="0x1027a">Tipo 1 / local</option><option :value="0x102d0">Tipo 2 / visitante</option><option :value="0x10326">Portero</option><option :value="0xe7d8">Bandera</option><option :value="0x1037c">Piel alternativa</option><option :value="0x103d2">Pelo alternativo</option></select></label><p>El cambio se convierte a BGR555. Los colores de piel/pelo alternativo y algunos gráficos se comparten entre equipos.</p>
        <div v-if="paletteData" class="palette-editor"><label v-for="(color,i) in paletteData.colors" :key="i">{{i}} <input type="color" :value="color" @change="editPalette(paletteData.offset+i*2,$event.target.value,$event)" /><button @click="restoreResource(`palette:${paletteData.offset+i*2}`)" :disabled="!isModified(`palette:${paletteData.offset+i*2}`)">↺</button></label></div><p v-else>Este equipo no tiene un registro alternativo de este tipo.</p>
        <div class="previews"><figure><RomImage :matrix="originalUniformMatrix" :colors="uniformColors(false)" label="Uniforme original" /><figcaption>Original</figcaption></figure><figure><RomImage :matrix="uniformMatrix" :colors="uniformColors(true)" label="Uniforme modificado" /><figcaption>Modificado</figcaption></figure></div><button @click="navigate('graphics')">Editar sprites y detalles</button></section>
      <section v-if="section==='graphics'"><h2>Pixel Art Maker</h2><select :value="graphic.id" aria-label="Seleccionar gráfico" @change="changeGraphic($event)"><option v-for="resource in resources" :key="resource.id" :value="resource.id">{{resource.label}}</option></select><p>{{graphic.label}} · {{graphic.kind==='composite'?'Capas 4bpp':graphic.bpp+'bpp'}} · {{originalGraphic.capacity}} bytes disponibles</p><p v-if="graphic.kind==='composite'" class="notice">Este recurso modifica el logo global de la portada.</p><p v-else-if="graphic.shared" class="notice">Recurso compartido: editar sus tiles afecta a todos los equipos que usan este sprite.</p><p v-else-if="graphic.kind==='label'" class="notice">El rótulo se guarda por equipo en un espacio reservado de 69 bytes; cualquier dibujo de 32 × 8 cabe.</p><p v-else class="notice">Las banderas se guardan por equipo y no cambian las de otros países. Los rótulos conservan sus referencias originales.</p><p v-if="graphic.label.includes('Logo')">Logo armado con sus dos capas y texto original. Los colores se ajustan a la paleta de la capa editada. El fondo sin tiles propios no se puede dibujar.</p>
        <div v-if="graphic.label==='Rótulo del equipo'">
          <h3>Nombre en las dos vistas del juego</h3><label>Nombre <input v-model="nameText" :maxlength="largeLabel.maxLetters" @input="namePreview=null" /></label><span>Hasta {{largeLabel.maxLetters}} caracteres A–Z/espacios para este slot.</span><button @click="previewTeamName">Previsualizar nombre</button>
          <RomImage :matrix="largeLabel.matrix" :colors="largeLabel.colors" label="Nombre rojo actual en selección de equipo" />
          <div v-if="namePreview" class="previews"><RomImage :matrix="namePreview.small.matrix" :colors="namePreview.small.colors" label="Nuevo rótulo pequeño" /><RomImage :matrix="namePreview.large.matrix" :colors="namePreview.large.colors" label="Nuevo nombre rojo de selección" /><button @click="applyTeamName">Aplicar nombre en ambas vistas</button><button @click="namePreview=null">Descartar previsualización</button></div>
          <button @click="restoreTeamName">Restaurar ambos nombres de este equipo</button><p>El campo Nombre actualiza ambos recursos. El dibujo libre de abajo modifica el rótulo pequeño; sus píxeles no se convierten automáticamente a letras.</p>
        </div>
        <p v-if="graphic.editableParts?.length===1">Edita la zona clara del pecho sobre el uniforme. Las demás partes del jugador sirven de contexto. Este patrón puede repetirse en otros equipos.</p><PixelEditor :flag="graphic.kind==='flag'" :apply-error="error" ref="pixel" :key="graphic.id" :matrix="graphic.matrix" :editable="graphic.editable" :highlight-editable="graphic.editableParts?.length===1" :original="originalGraphic.matrix" :original-colors="originalGraphic.colors" :colors="graphic.colors" @apply="applyGraphic" /><button @click="restoreGraphic" :disabled="!graphicModified">Restaurar recurso en ROM</button>
      </section>
      <section v-if="section==='audio'"><h2>Audio · muestras BRR</h2><p>Las muestras no contienen una frecuencia WAV. El DSP consume 32000 × pitch / 4096 muestras/s. El juego calcula el pitch por evento; esos eventos aún no están vinculados al catálogo. Este control es de inspección.</p><select v-model.number="sampleIndex" @change="previewAudio"><option v-for="(sample,i) in audioSamples" :key="i" :value="i">{{sample.name}}</option></select><label>Pitch DSP <input type="number" min="1" max="16383" v-model.number="pitch" @change="clearAudio" /></label><span>{{audioRate.toFixed(2)}} Hz</span><button @click="previewAudio">Previsualizar ROM</button><label><input type="checkbox" v-model="audioLoop" /> Repetir preview</label><p>{{audioInfo.capacity}} bytes BRR disponibles · {{(audioInfo.capacity/9*16/audioRate).toFixed(3)}} s de capacidad</p><p v-if="audioInfo.reason" class="notice">{{audioInfo.reason}} Reemplazo WAV deshabilitado.</p><p>La música secuenciada requiere editar eventos/instrumentos y emular el SPC700. Las muestras musicales listadas son fragmentos o instrumentos, no un editor de canciones.</p><label>Reemplazar muestra <input type="file" accept=".wav" :disabled="!!audioInfo.reason" @change="importWav" /></label><p v-if="audioReplacement">WAV convertido a BRR: {{audioReplacement.patch.bytes.length}} bytes. Se rellena con silencio hasta la capacidad original. La cuantización BRR puede degradar el audio.</p><audio v-if="audioUrl" ref="audio" :src="audioUrl" controls :loop="audioLoop" /><button v-if="audioUrl" @click="$refs.audio.pause();$refs.audio.currentTime=0">Detener</button><canvas v-show="audioUrl" ref="waveform" width="700" height="100" class="waveform" aria-label="Forma de onda" /><button @click="applyAudio" :disabled="!audioReplacement">Aplicar WAV convertido</button><button @click="restoreAudio" :disabled="!isModified(`audio:${audioInfo.offset}`)">Restaurar muestra</button></section>
      <section v-if="section==='project'"><h2>Proyecto y cambios</h2><p>SHA-256: <code>{{project.hash}}</code></p><p>{{saveStatus}}</p><button @click="exportProject">Descargar proyecto editable</button><label>Importar proyecto <input type="file" accept=".json" @change="importProject" /></label><button @click="reset">Restaurar todo</button><p>El proyecto descargado incluye tu ROM original y modificaciones. El archivo se conserva localmente.</p><ul><li v-for="patch in patches" :key="patch.id">{{patch.label}} · 0x{{patch.offset.toString(16)}} · {{patch.bytes.length}} bytes <button @click="restoreResource(patch.id)">Restaurar</button></li></ul><p v-if="!patches.length">Sin modificaciones. La exportación será idéntica al archivo original.</p><p>La exportación valida todos los recursos y equipos. No se ha validado ejecución en emulador todavía.</p></section>
      <dialog ref="hairDialog" v-if="hairPlayer!==null" class="hair-dialog" @cancel="hairPlayer=null"><h3>Elegir pelo · {{team.players[hairPlayer].name}}</h3><div class="hair-options"><button v-for="(option,i) in hairOptions" :key="i" @click="editPlayer(hairPlayer,'hair',i);hairPlayer=null"><RomImage compact :matrix="option.head" :colors="option.headColors" :label="`Estilo ${i}`" />{{i}}</button></div><button @click="hairPlayer=null">Cerrar</button></dialog>
    </div>
  </div><p v-else role="status">{{error||'Preparando proyecto…'}}</p>
</template>
<script>
import {markRaw} from 'vue';
import RomImage from './RomImage.vue';import PixelEditor from './PixelEditor.vue';
import {readFormation,formationPatch} from '../rom/formations.mjs';
import {RomProject} from '../rom/project.mjs';import {loadProject,storeProject} from '../rom/project-store.mjs';
import {DELUXE_TEAMS,readDeluxeTeam} from '../rom/deluxe.mjs';import {playerOffsets,playerPatches,POSITIONS,STATS} from '../rom/players.mjs';import {deluxeAppearance} from '../rom/appearance.mjs';
import {bigLabel,renameTeamPatches,restoreTeamLabelPatches} from '../rom/team-labels.mjs';
import {word,loRom,palette,tiles} from '../rom/binary.mjs';import {graphicResources,graphicPatches,flagPatches,smallLabelPatches,flagPalettePatches,rgb555} from '../rom/graphics.mjs';
import {AUDIO_SAMPLES,readAudioSample,wavBlob} from '../rom/audio.mjs';import {audioRegion,pitchRate,parseWav,replacementAudio} from '../rom/audio-edit.mjs';
const download=(bytes,name,type)=>{const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export default {
  components:{RomImage,PixelEditor},props:{input:Uint8Array},emits:['import-rom'],
  data(){return {project:null,rom:null,revision:0,teamIndex:0,team:null,error:'',saveError:'',saveStatus:'',storageBlocked:false,saveChain:Promise.resolve(),loadVersion:0,saveVersion:0,section:'dashboard',sections:{dashboard:'Resumen',teams:'Equipos',players:'Jugadores',appearance:'Apariencia',graphics:'Gráficos',audio:'Audio',project:'Proyecto'},teams:DELUXE_TEAMS,positions:POSITIONS,stats:STATS,search:'',sortKey:'index',positionFilter:'',selectedPlayers:[],batchStat:'speed',batchValue:5,copySource:0,formationSource:0,hairPlayer:null,paletteTable:0x1027a,graphicId:'',nameText:'',namePreview:null,audioSamples:AUDIO_SAMPLES,sampleIndex:0,pitch:1300,audioUrl:'',audioLoop:false,audioReplacement:null};},
  computed:{
    patches(){this.revision;return this.project.patches;},canUndo(){this.revision;return this.project.canUndo;},canRedo(){this.revision;return this.project.canRedo;},
    formation(){return readFormation(this.rom,this.teamIndex);},
    rows(){return this.team.players.map((player,index)=>({player,index})).filter(r=>r.player.name.toLowerCase().includes(this.search.toLowerCase())&&(!this.positionFilter||r.player.position===Number(this.positionFilter))).sort((a,b)=>{const k=this.sortKey,av=k==='index'?a.index:a.player[k],bv=k==='index'?b.index:b.player[k];return typeof av==='string'?av.localeCompare(bv):av-bv;});},
    hairOptions(){const player=this.team.players[this.hairPlayer]||this.team.players[0];return Array.from({length:14},(_,hair)=>deluxeAppearance(this.rom,this.teamIndex,{...player,hair}));},
    resources(){return graphicResources(this.rom,this.teamIndex);},graphic(){return this.resources.find(r=>r.id===this.graphicId)||this.resources[0];},originalGraphic(){return graphicResources(this.project.original,this.teamIndex).find(r=>r.id===this.graphic.id);},
    largeLabel(){return bigLabel(this.rom,this.teamIndex);},
    graphicModified(){const r=this.graphic,originalBytes=this.project.original;if(r.parts)return this.originalGraphic.parts.some((p,i)=>(!r.editableParts||r.editableParts.includes(i))&&this.rom.subarray(p.offset,p.offset+p.capacity).some((b,j)=>b!==originalBytes[p.offset+j]));const original=this.originalGraphic;return JSON.stringify(this.graphic.matrix)!==JSON.stringify(original.matrix)||JSON.stringify(this.graphic.colors)!==JSON.stringify(original.colors);},
    paletteData(){const pointer=word(this.rom,this.paletteTable+this.teamIndex*2);if(!pointer)return null;const offset=loRom(0x890000|pointer)+2,count=(word(this.rom,offset-2)+1)/2;return {offset,colors:palette(this.rom,offset,count)};},
    uniformMatrix(){return this.resources.find(r=>r.label.startsWith(this.paletteTable===0x10326?'Portero completo':'Jugador completo')).matrix;},
    originalUniformMatrix(){return graphicResources(this.project.original,this.teamIndex).find(r=>r.label.startsWith(this.paletteTable===0x10326?'Portero completo':'Jugador completo')).matrix;},
    audioRate(){try{return pitchRate(this.pitch);}catch{return 1;}},audioInfo(){return audioRegion(this.rom,this.audioSamples[this.sampleIndex]);},
  },
  watch:{hairPlayer(value){if(value!==null)this.$nextTick(()=>this.$refs.hairDialog?.showModal());},input(){this.initialize();}},mounted(){this.initialize();window.addEventListener('keydown',this.shortcuts);window.addEventListener('beforeunload',this.beforeLeave);},beforeUnmount(){this.loadVersion++;this.clearAudio();window.removeEventListener('keydown',this.shortcuts);window.removeEventListener('beforeunload',this.beforeLeave);},
  methods:{
    async initialize(){const version=++this.loadVersion;this.error='';this.saveError='';this.storageBlocked=false;this.clearAudio();try{let project=await RomProject.create(this.input);try{const saved=await loadProject(project.hash);if(saved){try{project=await RomProject.import(saved);}catch(e){this.storageBlocked=true;throw e;}}}catch(e){this.saveError=`No se pudo restaurar el guardado: ${e.message}`;}if(version!==this.loadVersion)return;this.project=markRaw(project);this.teamIndex=0;this.graphicId='';this.refresh();if(!this.storageBlocked)this.save();else this.saveStatus='Guardado anterior no validado';}catch(e){this.error=e.message;}},
    refresh(){this.rom=markRaw(this.project.bytes());this.team=readDeluxeTeam(this.rom,this.teamIndex);this.revision++;},
    changed(){this.refresh();this.save();},
    retrySave(){if(this.storageBlocked&&!confirm('El guardado anterior no pudo validarse. ¿Reemplazarlo por el proyecto actual?'))return;this.storageBlocked=false;this.save();},
    save(){if(this.storageBlocked)return;const record=this.project.record(),version=++this.saveVersion;this.saveStatus='Guardando…';this.saveChain=this.saveChain.catch(()=>{}).then(()=>storeProject(record)).then(()=>{if(version===this.saveVersion){this.saveStatus=`Guardado: ${new Date().toLocaleString()}`;this.saveError='';}}).catch(e=>{if(version===this.saveVersion){this.saveStatus='Cambios sin guardar';this.saveError=e.message||'Error de cuota o almacenamiento.';}});},
    act(fn){this.error='';try{fn();}catch(e){this.error=e.message;}},
    pending(){return !!this.$refs.pixel?.dirty||!!this.$refs.pixel?.importImage||!!this.audioReplacement||!!this.namePreview;},allowNavigate(){return !this.pending()||confirm('Hay una previsualización que todavía no se aplicó a la ROM. ¿Descartar esa previsualización?');},
    navigate(section){if(this.section===section)return;if(!this.allowNavigate())return;this.clearAudio();this.namePreview=null;this.section=section;},changeTeam(event){if(!this.allowNavigate()){event.target.value=this.teamIndex;return;}this.teamIndex=Number(event.target.value);this.graphicId='';this.nameText='';this.namePreview=null;this.selectedPlayers=[];this.refresh();},
    changeGraphic(event){if(!this.allowNavigate()){event.target.value=this.graphic.id;return;}this.namePreview=null;this.graphicId=event.target.value;},
    formationOf(i){return readFormation(this.project.original,i);},formationY(slot){const base=slot.role===1||slot.role===5?78:slot.role===2||slot.role===6?50:22;return Math.max(6,Math.min(94,base+slot.depth));},
    editTeamLabel(){this.graphicId=this.resources.find(r=>r.label==='Rótulo del equipo').id;this.navigate('graphics');},
    previewTeamName(){this.act(()=>{if(this.$refs.pixel?.dirty)throw new Error('Aplica o descarta el dibujo pendiente antes de preparar un nombre.');const patches=renameTeamPatches(this.project.original,this.rom,this.teamIndex,this.nameText),preview=this.rom.slice();patches.forEach(p=>preview.set(p.bytes,p.offset));this.namePreview=markRaw({patches,small:graphicResources(preview,this.teamIndex).find(r=>r.label==='Rótulo del equipo'),large:bigLabel(preview,this.teamIndex)});});},
    applyTeamName(){this.act(()=>{if(this.$refs.pixel?.dirty)throw new Error('Descarta el dibujo pendiente antes de aplicar el nombre preparado.');this.project.transaction(this.namePreview.patches);this.namePreview=null;this.changed();});},
    restoreTeamName(){if(!this.allowNavigate())return;this.act(()=>{this.project.transaction(restoreTeamLabelPatches(this.project.original,this.rom,this.teamIndex));this.namePreview=null;this.changed();});},
    applyFormation(){this.act(()=>{this.project.transaction([formationPatch(this.project.original,this.teamIndex,this.formationSource)]);this.changed();});},
    editPlayer(index,key,value,event){this.act(()=>{this.project.transaction(playerPatches(this.rom,this.teamIndex,index,{[key]:value}));this.changed();});if(this.error&&event)event.target.value=this.team.players[index][key];},
    selectAll(checked){this.selectedPlayers=checked?this.rows.map(r=>r.index):[];},batch(){this.act(()=>{this.project.transaction(this.selectedPlayers.flatMap(i=>playerPatches(this.rom,this.teamIndex,i,{[this.batchStat]:this.batchValue})));this.changed();});},
    copyRoster(){if(!confirm(`¿Reemplazar los 20 jugadores de ${this.teams[this.teamIndex]} por la plantilla de ${this.teams[this.copySource]}? Los gráficos y el equipo no se duplican.`))return;this.act(()=>{const source=readDeluxeTeam(this.rom,this.copySource);this.project.transaction(source.players.flatMap((p,i)=>playerPatches(this.rom,this.teamIndex,i,Object.fromEntries(['name','no','position','hair','skin',...this.stats].map(k=>[k,p[k]])),false)));this.changed();});},
    isModified(id){return this.patches.some(p=>p.id===id);},isPlayerModified(i){const p=playerOffsets(this.rom,this.teamIndex,i);return this.isModified(`name:${p.name}`)||this.isModified(`attributes:${p.attributes}`);},
    restorePlayer(i){this.act(()=>{const p=playerOffsets(this.rom,this.teamIndex,i);this.project.transaction([...this.project.restorePatches(`name:${p.name}`),...this.project.restorePatches(`attributes:${p.attributes}`)]);this.changed();});},
    paletteUsers(offset){const affected=[];for(let team=0;team<36;team++)for(const table of [0x1027a,0x102d0,0x10326,0x1037c,0x103d2,0xe7d8]){const pointer=word(this.rom,table+team*2);if(!pointer)continue;const start=loRom(0x890000|pointer)+2,count=(word(this.rom,start-2)+1)/2;if(offset>=start&&offset<start+count*2&&!affected.includes(this.teams[team]))affected.push(this.teams[team]);}return affected;},
    editPalette(offset,color,event){const users=this.paletteUsers(offset);if(!confirm(`Este color afecta a jugadores o recursos que usan esta paleta: ${users.join(', ')}. ¿Aplicar color?`)){if(event)event.target.value=palette(this.rom,offset,1)[0];return;}this.act(()=>{this.project.transaction([{id:`palette:${offset}`,label:`Color de paleta · ${users.join(', ')}`,offset,bytes:rgb555(color)}]);this.changed();});if(this.error&&event)event.target.value=palette(this.rom,offset,1)[0];},
    skinColor(index,color,event){const p=this.team.players[index];let table=p.position===1?0x10326:0x1027a,indexInPalette=p.position===1?3:4;if(p.skin&&word(this.rom,0x1037c+this.teamIndex*2)){table=0x1037c;indexInPalette=2;}const offset=loRom(0x890000|word(this.rom,table+this.teamIndex*2))+2+indexInPalette*2;this.editPalette(offset,color,event);},
    uniformColors(modified){const rom=modified?this.rom:this.project.original,table=[0x1027a,0x102d0,0x10326].includes(this.paletteTable)?this.paletteTable:0x1027a,pointer=word(rom,table+this.teamIndex*2),count=table===0x10326?11:16,colors=palette(rom,loRom(0x890000|pointer)+2,count);if(table===0x10326)colors.unshift('transparent');while(colors.length<16)colors.push('transparent');colors[0]='transparent';return colors;},
    applyGraphic(matrix,colors){this.act(()=>{if(this.namePreview)throw new Error('Aplica o descarta el nombre preparado antes de guardar un dibujo.');const resource=this.graphic,affected=resource.kind==='composite'?[]:this.teams.filter((_,i)=>graphicResources(this.project.original,i).some(r=>r.id===resource.id));if(affected.length>1&&!confirm(`Este gráfico es compartido por ${affected.join(', ')}. ¿Aplicar a todos sus usos?`))return;this.project.transaction([...graphicPatches(this.project.original,this.rom,resource,matrix),...(resource.kind==='flag'&&colors?flagPalettePatches(this.rom,this.teamIndex,colors):[])]);this.changed();});},
    restoreGraphic(){if(!this.allowNavigate())return;this.act(()=>{const r=this.graphic;if(r.kind==='flag')this.project.transaction([...flagPatches(this.project.original,this.rom,this.teamIndex,this.originalGraphic.matrix),...flagPalettePatches(this.rom,this.teamIndex,this.originalGraphic.colors)]);else if(r.kind==='label')this.project.transaction(smallLabelPatches(this.project.original,this.rom,this.teamIndex,this.originalGraphic.matrix));else if(r.parts)this.project.transaction(r.parts.flatMap((p,i)=>r.editableParts&&!r.editableParts.includes(i)?[]:this.project.restorePatches(p.id)));else this.project.restore(r.id);this.changed();});},restoreResource(id){this.act(()=>{this.project.restore(id);this.changed();});},
    history(redo){if(!this.allowNavigate())return;this.clearAudio();this.namePreview=null;this.act(()=>{redo?this.project.redo():this.project.undo();this.changed();});},
    reset(){if(!confirm('¿Restaurar todos los recursos de la ROM original? Puedes deshacer la operación.'))return;this.clearAudio();this.namePreview=null;this.act(()=>{this.project.reset();this.changed();});},
    exportRom(){if(this.pending()){this.error='Aplica o descarta la previsualización pendiente antes de exportar.';return;}this.act(()=>download(this.project.exportRom(),`ISSD-editado.${this.project.headerSize?'smc':'sfc'}`,'application/octet-stream'));},
    exportProject(){if(this.pending()){this.error='Aplica o descarta la previsualización pendiente antes de descargar el proyecto.';return;}this.act(()=>download(JSON.stringify(this.project.record()),'ISSD-proyecto.json','application/json'));},
    async importProject(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>8000000){this.error='El proyecto supera el límite de 8 MB.';return;}try{const record=JSON.parse(await file.text()),project=await RomProject.import(record);if(!confirm('¿Abrir el proyecto importado y reemplazar su guardado local?'))return;await storeProject(project.record());this.$emit('import-rom',new File([project.exportOriginal()],'ISSD-proyecto.sfc'));}catch(e){this.error=e.message;}},
    clearAudio(){this.$refs.audio?.pause();if(this.audioUrl)URL.revokeObjectURL(this.audioUrl);this.audioUrl='';this.audioReplacement=null;},
    showAudio(samples,rate,autoplay=false){if(this.audioUrl)URL.revokeObjectURL(this.audioUrl);this.audioUrl=URL.createObjectURL(wavBlob(samples,Math.round(rate)));const url=this.audioUrl;this.$nextTick(()=>{if(this.audioUrl!==url)return;if(autoplay)this.$refs.audio?.play().catch(e=>{if(e.name!=='AbortError'&&this.audioUrl===url)this.error='No se pudo reproducir automáticamente. Usa los controles de audio para iniciar la reproducción.';});const canvas=this.$refs.waveform;if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#176be0';ctx.beginPath();for(let x=0;x<canvas.width;x++){const start=Math.floor(x*samples.length/canvas.width),end=Math.max(start+1,Math.floor((x+1)*samples.length/canvas.width));let min=0,max=0;for(let i=start;i<end;i++){min=Math.min(min,samples[i]||0);max=Math.max(max,samples[i]||0);}ctx.moveTo(x,50-min/32768*45);ctx.lineTo(x,50-max/32768*45);}ctx.stroke();});},
    previewAudio(){this.act(()=>{this.clearAudio();this.showAudio(readAudioSample(this.rom,this.audioSamples[this.sampleIndex]),pitchRate(this.pitch),true);});},
    async importWav(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>20000000){this.error='El WAV supera 20 MB.';return;}const sample=this.audioSamples[this.sampleIndex],pitch=this.pitch;try{const wav=parseWav(await file.arrayBuffer());if(sample!==this.audioSamples[this.sampleIndex]||pitch!==this.pitch)throw new Error('El audio seleccionado cambió durante la importación. Vuelve a elegir el WAV.');const replacement=replacementAudio(this.rom,sample,wav,pitch);this.audioReplacement=markRaw(replacement);this.showAudio(replacement.samples,replacement.rate);}catch(e){this.error=e.message;}},
    applyAudio(){this.act(()=>{this.project.transaction([this.audioReplacement.patch]);this.audioReplacement=null;this.changed();});},restoreAudio(){this.clearAudio();this.restoreResource(`audio:${this.audioInfo.offset}`);},
    shortcuts(event){if(['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)||event.target.isContentEditable)return;if((event.ctrlKey||event.metaKey)&&['z','y'].includes(event.key.toLowerCase())){event.preventDefault();if(this.$refs.pixel){event.shiftKey||event.key==='y'?this.$refs.pixel.redo():this.$refs.pixel.undo();}else this.history(event.shiftKey||event.key==='y');}},
    beforeLeave(event){if(this.pending()||this.saveStatus==='Guardando…'||this.saveError){event.preventDefault();event.returnValue='';}},
  }
};
</script>
<style scoped>
.studio{display:grid;grid-template-columns:190px minmax(0,1fr);gap:24px;margin-top:24px}.studio aside{background:#172a40;color:white;border-radius:12px;padding:18px;align-self:start;position:sticky;top:16px}.studio aside button{display:block;width:100%;text-align:left;background:transparent;border:0;color:white;padding:10px;margin:2px 0;border-radius:6px}.studio aside .selected{background:#176be0}.workspace{min-width:0;background:#f9fbfd;border:1px solid #d4dce4;border-radius:12px;padding:20px}header,.toolbar,.skin-cell,.hair-options,.previews{display:flex;align-items:center;gap:8px;flex-wrap:wrap}button,input,select{padding:7px;font:inherit;border:1px solid #bbc8d6;border-radius:5px;margin:3px}button{cursor:pointer}button:disabled{opacity:.45;cursor:default}.primary{background:#176be0;color:white;border:0}.notice{padding:10px;background:#fff0ca}.error{color:#a32121}.table-scroll{overflow:auto}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #d4dce4;padding:6px;text-align:left;vertical-align:top}th{background:#edf3f9}.number{width:50px}.name{width:96px}.modified{background:#fff8df}details label{display:block;white-space:nowrap}.hair{display:flex;align-items:center;gap:5px}.skin-color{width:20px;height:20px;padding:0;border:0;flex:none}.skin-color::-webkit-color-swatch-wrapper{padding:0}.skin-color::-webkit-color-swatch{border:0}.palette-editor{display:flex;flex-wrap:wrap;gap:12px}.palette-editor label{display:flex;align-items:center;gap:4px}.palette-editor input{width:44px;height:36px;padding:2px}.hair-dialog{position:fixed;inset:20%;z-index:20;box-shadow:0 0 0 100vmax #0008;border:0;border-radius:12px}.waveform{width:100%;max-width:700px;background:#edf3f9}.pitch{display:block;width:300px;max-width:100%;margin:16px 0}code{overflow-wrap:anywhere;font-size:11px}audio{display:block;margin:12px 0}figure{margin:12px}@media(max-width:800px){.studio{grid-template-columns:1fr}.studio aside{position:static}.studio aside button{display:inline-block;width:auto}.workspace{padding:10px}}
</style>
